/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface TextEditor {
    /**
    * The plugins to activate
    * @example <text-editor plugins={[  {    plugin: PluginA,    config: {      some: 'config here'    }  },  {    plugin: PluginB,  },  ... ]}></text-editor>
    */
    'plugins': Array<iEditorPlugins>;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLTextEditorElement extends Components.TextEditor, HTMLStencilElement {}
  var HTMLTextEditorElement: {
    prototype: HTMLTextEditorElement;
    new (): HTMLTextEditorElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'text-editor': HTMLTextEditorElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppRoot {}
  interface TextEditor {
    /**
    * The plugins to activate
    * @example <text-editor plugins={[  {    plugin: PluginA,    config: {      some: 'config here'    }  },  {    plugin: PluginB,  },  ... ]}></text-editor>
    */
    'plugins'?: Array<iEditorPlugins>;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'text-editor': TextEditor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'text-editor': LocalJSX.TextEditor & JSXBase.HTMLAttributes<HTMLTextEditorElement>;
    }
  }
}


